# Generated by Django 6.0.4 on 2026-05-10 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kasalxona nomi')),
                ('hospital_type', models.CharField(choices=[('davlat', 'Davlat kasalxonasi'), ('xususiy', 'Xususiy klinika'), ('poliklinika', 'Poliklinika'), ('shifoxona', 'Shifoxona'), ('tez yordam', 'Tez yordam markazi')], max_length=50, verbose_name='Turi')),
                ('region', models.CharField(choices=[('toshkent', 'Toshkent'), ('andijon', 'Andijon'), ('fargona', "Farg'ona"), ('namangan', 'Namangan'), ('samarqand', 'Samarqand'), ('buxoro', 'Buxoro'), ('qashqadaryo', 'Qashqadaryo'), ('surxondaryo', 'Surxondaryo'), ('xorazm', 'Xorazm'), ('navoiy', 'Navoiy'), ('jizzax', 'Jizzax'), ('sirdaryo', 'Sirdaryo'), ('qoraqalpogiston', "Qoraqalpog'iston")], max_length=50, verbose_name='Viloyat')),
                ('address', models.CharField(max_length=300, verbose_name='Manzil')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Veb-sayt')),
                ('bed_count', models.PositiveIntegerField(default=0, verbose_name="O'rin soni")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kasalxona',
                'verbose_name_plural': 'Kasalxonalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Otasining ismi')),
                ('age', models.PositiveIntegerField(verbose_name='Yosh')),
                ('position', models.CharField(choices=[('shifokor', 'Shifokor'), ('hamshira', 'Hamshira'), ('jarroh', 'Jarroh'), ('laborant', 'Laborant'), ('radiolog', 'Radiolog'), ('stomatolог', 'Stomatolog'), ('pediatr', 'Pediatr'), ('kardiolog', 'Kardiolog'), ('nevropatolog', 'Nevropatolog'), ('anesteziolog', 'Anesteziolog'), ('farmatsevt', 'Farmatsevt'), ('psixiatr', 'Psixiatr'), ('boshqa', 'Boshqa')], max_length=50, verbose_name='Lavozim')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Mutaxassislik')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Tajriba (yil)')),
                ('shift', models.CharField(choices=[('kunduzgi', 'Kunduzgi'), ('tungi', 'Tungi'), ('aralash', 'Aralash')], default='kunduzgi', max_length=20, verbose_name='Ish vaqti')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/', verbose_name='Rasm')),
                ('salary', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name="Maosh (so'm)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('hired_date', models.DateField(blank=True, null=True, verbose_name='Ishga kirgan sana')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='frontend.hospital', verbose_name='Kasalxona')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
